project:
  type: website
  output-dir: docs
website:
  title: "Mon portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: À propos
      - href: scene3D.qmd
        text: Scene3D
  search: false
format:
  html:
    theme: cosmo
    toc: true